ci:
  skip:
    - pytest

default_language_version:
    python: python3.9
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args:
        - --fix
        - --unsafe-fixes
      - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: v1.20.4
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: poetry run pytest tests/
        language: system
        pass_filenames: false
        always_run: true
